databases:
  - name: bytes
    databaseName: bytes
    user: bytes_user

services:
  - type: web
    name: bytes
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bytes
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false